/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;

/**
 *
 * @author hp
 */
public class caca extends javax.swing.JPanel {

    /**
     * Creates new form caca
     */
    public caca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        panelRound1 = new swing.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NumeroFacture = new javax.swing.JLabel();
        DateFacture = new javax.swing.JLabel();
        NomClient = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        DateClient = new javax.swing.JLabel();
        NumeroClient = new javax.swing.JLabel();
        adresseClient = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ProjetName = new javax.swing.JLabel();
        statusProjet = new javax.swing.JLabel();
        DepenseProjet = new javax.swing.JLabel();
        DateDebut = new javax.swing.JLabel();
        DateFin = new javax.swing.JLabel();
        MotantTotal = new javax.swing.JLabel();
        dateDebut = new javax.swing.JLabel();
        DateFinActivite = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        EtatPaiement = new javax.swing.JLabel();

        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pdfProjet.png"))); // NOI18N
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 996, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pdfProjet2.png"))); // NOI18N
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 896, -1, 449));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logoLoginRegister.png"))); // NOI18N
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 170, 70));

        NumeroFacture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumeroFacture.setText("Numero Facture");
        panelRound1.add(NumeroFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 100, 30));

        DateFacture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateFacture.setText("DateF Projet");
        panelRound1.add(DateFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 170, 30));

        NomClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomClient.setText("Nom Client");
        panelRound1.add(NomClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 220, 30));

        contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact.setText("Contact");
        panelRound1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 200, 30));

        Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email.setText("Email");
        panelRound1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 510, 20));

        DateClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateClient.setText("10/10/2023");
        panelRound1.add(DateClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 494, 140, 20));

        NumeroClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumeroClient.setText("10/10/2023");
        panelRound1.add(NumeroClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 370, 110, 20));

        adresseClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adresseClient.setText("Antaravay");
        panelRound1.add(adresseClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 130, 20));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("0003");
        panelRound1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 100, 20));

        ProjetName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProjetName.setText("Java");
        panelRound1.add(ProjetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 566, 330, 30));

        statusProjet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusProjet.setText("Etat");
        panelRound1.add(statusProjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, 120, 30));

        DepenseProjet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DepenseProjet.setText("2000000AR");
        panelRound1.add(DepenseProjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 230, 30));

        DateDebut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateDebut.setText("DateD Projet");
        panelRound1.add(DateDebut, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 190, 20));

        DateFin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateFin.setText("DateF Projet");
        panelRound1.add(DateFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 160, 20));

        MotantTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelRound1.add(MotantTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 730, 220, 40));

        dateDebut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateDebut.setText("10/10/2023");
        panelRound1.add(dateDebut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 810, 160, 30));

        DateFinActivite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateFinActivite.setText("10/10/2023");
        panelRound1.add(DateFinActivite, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 810, 140, 30));

        description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description.setText("blabla");
        panelRound1.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 790, 560, 20));

        EtatPaiement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtatPaiement.setText("Payer");
        panelRound1.add(EtatPaiement, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 840, 160, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateClient;
    private javax.swing.JLabel DateDebut;
    private javax.swing.JLabel DateFacture;
    private javax.swing.JLabel DateFin;
    private javax.swing.JLabel DateFinActivite;
    private javax.swing.JLabel DepenseProjet;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel EtatPaiement;
    private javax.swing.JLabel MotantTotal;
    private javax.swing.JLabel NomClient;
    private javax.swing.JLabel NumeroClient;
    private javax.swing.JLabel NumeroFacture;
    private javax.swing.JLabel ProjetName;
    private javax.swing.JLabel adresseClient;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel dateDebut;
    private javax.swing.JLabel description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollBar jScrollBar1;
    private swing.PanelRound panelRound1;
    private javax.swing.JLabel statusProjet;
    // End of variables declaration//GEN-END:variables
}
